paypal:
  client-id: ATiinTr3wGfts-amNuOMPyvILtASKd3sRaIetQrYU2J0DwvT1svjQIrmWzqevXlv4rIHA7JyBt4ZSg0a
  client-secret: ECMeQO6886TCd3ObHG1JT7KL9ajGSFXB4VuQDDEpyuF3yTDhds8jswfnUoJprb_GBxmzg5_anqMi0IlQ
  mode: sandbox